language: node_js
node_js:
  - 10
install:
  - yarn
  - yarn build-packages
script:
  - yarn lint
  - yarn prettier:check
  - yarn test
deploy:
  - provider: script
    script: bin/publish.sh
    skip_cleanup: true
    on:
      branch: master
      tags: false
env:
  global:
    secure: USELSJq6Erf4slXgSUxHRvsHXsEtxTu9huLhc3cZqirs4XXp24vAeKa6T7CMoGmg05BhW3Fe63/GPJxkqwvrGEd5L1ry8D2SX5U8IBMGCKU3LUet25D89Du1Ge2H/ktvvm4+cUMFwGHXlXsCyrcz2CgWcjW3L9qxP13RXh9eKkf+vC8y9GmWKNRrsp2ZdgXseZLcqJaR3COuy0btCWOGrIST4uXtHUPczW+/ptTGsqkLlw6W/MFR5AI66J1Ucub7Kx0On30Wf3W61WaMWIV++xqr2IQjC9ysval/4BU3cRMIi9P/xQndiLM6+b/p9QpVMv8u6nzFSjufbozRMNLostgWgdhXwwntHE+S74Az/nz7nhZYsAgGhM4Vp4DokzSfDgBs77mphsOLnIbP+HP7oTgi7NzWtFe+nCPo210Lc+1++bSNKDoB5tbdaQkBeFhbT/fEVAkMi8mH5w9AQV1f3VfcbKzQ6zGihLTQEo21cd9boKJDWx5fv0QbjIeMIHKWKwupYzxcBJALNBHy3xvx63sgwXgQz5dAYHHfbFLyBlpl6I9uZ80EMozktcg9SApKt6qLfDsnrGinHl3fKlPy8I5qyFx8a4R7BH3nD/wS7JCQhtuhCnizJSeKmvomB3jACz/bSR7wNWPrPW1IJ64ZfZaF8v8GknDjmC+hTqAkToQ=
