language: node_js
node_js:
- 10
install:
- yarn
- yarn build-packages
script:
- yarn lint
- yarn prettier:check
- yarn test
deploy:
- provider: script
  script: bin/publish.sh
  skip_cleanup: true
  on:
    branch: master
    tags: false
env:
  global:
    secure: I/7EhnIpoL7Xy2Pzbf9LMai9Wt/cVa8q2IJVR/GhsSgvT2tCFG/Q/8EeYGnMKhRqbwvc4p2glu4nAHaeJbsxPg1AeuaKuKNXGEc0S6QxN1NUg0X3UiP8eGfOyhYAANEZH3uhd7xGTsKOOewILOihngjCEZ/XPvrauiKdYQZaG95WLH6QHc1VvytWi7GKZnXdTkFdh0I6yGeVR48evmLageT/nTT767eBqA6xnR1Sktzwy8saDeTjv8tR6i861isgy+s+YaMOqW+/uK/oV3UjiEfEJsUAMa9vi/Jetu7GqH/g78+17F4dcq46dP/pc+p1xfM4YG/fl4w0XItjnUypP0j8CCmVxpWwT5X0Cipzzwswnso9vDZM9Fr999khyb+pWi7T8uvVhD0gtOy6S3ppaxr7+Mbxzd2I7cEe4FhIRXuXgMJ9mkmKjdfo3hdSd6iqnyP1TOcgaP71fTCD07OQd55YUARDFPEA2O9EavjSPHiQlT3X9tOM0Zpp+mB6SsndIK5zRGNclHAa6gSeVpNzGZgkIsNx2+uzokHfgyW1i7JWnNDm6VZ/BWnju1cKRotOYnNT0g0VM9a82CElJS1YffR27/VUf5djKdiZKnQ/nUhVUNmT4TXhDfqtl7cFVjR+6RixsE5+ujRKvsRMpD4XltGBT3u8JsWRoX9CnewtZpY=
